snapshot-labs/snapshot-webhook

src/discord.ts
```
TypeError: Cannot read property 'permissions' of null
at /app/src/discord.ts:78:30
at Generator.next (<anonymous>)
at /app/src/discord.ts:8:71
at new Promise (<anonymous>)
at __awaiter (/app/src/discord.ts:4:12)
```
=> [Fix] Cannot read property 'permissions' of null

src/discord.ts
All the columns in the tables are `NOT NULL`, but when creating a new discord subscriber, the query does not explicitly mention the `updated` field, making the query fail.
Add a value for the `updated` field when inserting a new row
=> fix: fix missing field for NOT NULL column

src/discord.ts, src/helpers/proposal.ts
Fix #57 
Links could be passed as space
Hub `/api` endpoint is returning a valid space when polling for an URL as space ID.
Move the space fetching to graphql instead
=> fix: use a more robust space verification

src/api.ts
When use input an invalid url while using the `/api/test` endpoint, it raises and send the error to sentry
Invalid user input such as invalid URL should not be logged to sentry, reducing noise
Fix #73 
- Do not sent the `INVALID_URL` error to sentry
=> fix: do not capture error on invalid user input

src/events.ts
Outgoing webhook to subscribers does not have timeout, and rely on OS timeout value, which is pretty high. We should send, then close all outgoing requests as fast as possible, and not have slow subscribers hogging our connections pools.
Set a lower timeout value for outgoing request: 15s
This will fix all the timeout errors in the log.
- Add `timeout` property to outgoing fetch request
- Use `node-fetch` instead of `cross-fetch`. This is a node-only project, we don't need browser nor react native support.
- Throw errors on `fetch` errors, else the `Promise.allSettled()` will always see all promises as resolved.
- Print a dedicate error message on time out errors
- add a slow subscriber to your database, like `https://httpstat.us/200?sleep=30000`
- `yarn dev`, and see outgoing requests in …
=> fix: add timeout on outgoing webhook requests

src/discord.ts
When creating a discord vote button from the proposal choices, the choice string is passed as-is to the button as label. In the case where choice is > 80 characters, it will trigger an exception from discord.js, which is expecting a button with max 80 characters.
Limit the number of characters in the button
Fix #75 
- Call `slice()` to limit the number of characters in the button to the limit set by discord.js
=> fix: limit the button label length

src/api.ts, src/index.ts, src/replay.ts
Requesting the root (https://webhook.snapshot.org/) is resulting in a 404 error.
The expected '/' route has been nested under /api
Move back the root router to index.ts
- `/` should display the usual JSON as other services
- add a catch-all routes to return 404 error as JSON, instead of express default format
- `yarn start`
- Go to `http://localhost:3000/`
- It should display a JSON object 
- Go to `http://localhost:3000/ddsddsd`
- It should display a JSON response, with status code 404
=> chore: fix 404 error on home page

package.json, src/helpers/metrics.ts, yarn.lock
The metrics logic is shared by a few other projects, and contains repetition.
To avoid repetition, extract the metrics bootstrapping task to an external NPM package
- Install @snapshot-labs/snapshot-metrics package
- Move the metrics bootstrapping to it
- Each project using the package should only have to define the custom metrics.
- Update the `express` package, which was causing typescript error when importing snapshot-metrics
- Go to `localhost/metrics`
- It should show the metrics endpoint
=> chore: use snapshot-metrics

.github/workflows/create-sentry-release.yml, .github/workflows/lint.yml
Current CI workflows are running on node 16, whereas the app is requiring node 18
Update CI tasks to run on node 18
- Update CI task to run on node 18
- N/A
=> chore: update CI workflows to use node 18

.github/workflows/lint.yml, src/helpers/utils.ts, src/replay.ts
Some calls to snapshot.js (`snapshot.utils.subgraphRequest`) are not wrapped in a try/catch, raising the Sentry error https://snapshot-labs.sentry.io/issues/4415907506/?project=4505506867707904&referrer=github_integration
Fix #92 
Fix [SNAPSHOT-WEBHOOK-J](https://snapshot-labs.sentry.io/issues/4415907506/?referrer=github_integration)
Wrap the call in a `try/catch`
- Wrap all `snapshot.utils.subgraphRequest` in a try/catch
- Add more contexts to the logged error messages
- Bump node version to 18 on the github actions workflows
- N/A
=> fix: fix missing try/catch on subgraph queries

src/providers/webhook.ts
Sending HTTP webhook using the `GET` method is failing. This error is not bubbling up to Sentry, as `Promise.allSettled` is eating the error.
Error is due to the presence of the `body` property, which is not allowed in a GET request
- Set the `body` property only if it is a `POST` request
- Use the `api/test` endpoint (depends on https://github.com/snapshot-labs/snapshot-webhook/pull/99)
=> fix: fix GET http request failing

.github/dependabot.yml, package.json, src/helpers/metrics.ts, yarn.lock
- Update snapshot-sentry to latest version (add support to capture JSON-RPC error)
- Update snapshot-metrics to latest version (add pushgateway support)
- Add dependabot to update @snapshot-labs packages
=> chore: upgrade metrics to support pushgateway

src/helpers/metrics.ts, src/providers/xmtp.ts
Use the existing `subscribers_per_type_count` to track the subscribers count, instead of having a dedicated metric
=> fix: use existing metrics to track XMTP subscribers count

src/helpers/schema.sql
Run following SQL on prod webhook DB
=> fix: Don't allow duplicates for URL + space

.github/workflows/test.yml, .gitignore, jest.config.ts, package.json, src/helpers/utils.ts, test/unit/helpers/utils.test.ts, yarn.lock
Fix #137 
- Skip webhooks for flagged proposals
- Add tests
=> fix: skip webhooks for flagged proposals

src/providers/index.ts
Following on https://discord.com/channels/955773041898573854/1031838169282392144/1182256340144508999
Disable provider because:
- pusher subscription is over the limit
- we don't use push notifications anymore on the UI
=> fix: disable unused Beams provider

src/providers/discord.ts
Fix error when discord bot permission is `null`
Fix #157 
Fix [SNAPSHOT-WEBHOOK-15](https://snapshot-labs.sentry.io/issues/4843545157/?referrer=github_integration)
=> fix: fix error when bot permissions is null

src/providers/discord.ts
Fix `event` variable not available in the capture scope
Fix #159 
Fix [SNAPSHOT-WEBHOOK-R](https://snapshot-labs.sentry.io/issues/4510290542/?referrer=github_integration)
=> fix: fix variable scope

src/providers/discord.ts
We are logging a lot of discord error, such as `Missing permission`, or `Channel not found`.
Those errors are not code related, and should not be logged on sentry, as we can not resolve them (these are more user errors)
Stop sending the errors on Sentry, and just log them with `console.error`, to be inline with what's already done with the user errors on the http webhook.
Fix SNAPSHOT-WEBHOOK-3
Fix SNAPSHOT-WEBHOOK-4
Fix SNAPSHOT-WEBHOOK-16
Fix SNAPSHOT-WEBHOOK-V
Fix SNAPSHOT-WEBHOOK-5
- Send all `DiscordAPIError` to console.error instead of Sentry
=> chore: stop sending discord error to sentry

src/api.ts
Ignore all `FetchError` from `api/test` endpoint, which are operation error from http (network timeout, error 500, etc ...).
Error details returned already as JSON RPC response, no need to log them to our error logger.
Fix SNAPSHOT-WEBHOOK-17
=> fix: ignore fetch error from test endpoint

src/helpers/metrics.ts, src/providers/walletconnectNotify.ts, src/types.ts
Fix #166 
Closes [SNAPSHOT-WEBHOOK-18](https://snapshot-labs.sentry.io/issues/4894434203/?referrer=github_integration)
- Fix error when `getSubscribersFromWalletConnect` is failing
- Remove `wait` method, using `snapshot.utils.sleep` instead
- Add `console.log`
=> fix: fix metrics error on walletconnectNotify subscribers fetch error

src/helpers/metrics.ts, src/providers/beams.ts, src/providers/discord.ts, src/providers/walletconnectNotify.ts, src/providers/webhook.ts, src/providers/xmtp.ts
The current instrumentation method only track the number of outgoing requests call, and assumes that one call = one message sent to one subscriber
This was true for HTTP, Discord and XMTP, but not for Beams and WalletConnect, which uses batch sending
This means that we do not have reliable metrics for number of messages sent to users for Beams and walletConnect
Add a new `http_webhook_outgoing_messages_count` metrics to track the number of messages sent to subscriber
=> feat: track number of outgoing webhook messages

src/providers/beams.ts, src/providers/discord.ts, src/providers/walletconnectNotify.ts, src/providers/webhook.ts, src/providers/xmtp.ts
Fix missing `provider` label in `outgoingMessages` metric introduced in #168
=> fix: fix missing provider property in outgoingMessages metric

src/helpers/metrics.ts, src/providers/walletconnectNotify.ts
Remove `GET /subscribers` lookup in-favor of chain-agnostic handling that is now built-into the `/notify` endpoint. Avoids expensive network requests and mapping logic. Instead, an arbitrary chain ID prefix can be used (in this case `eip155:1`) and Notify Server will now find the correct account with the same address internally.
=> fix: avoid expensive network requests by using chain agnostic notify

package.json, yarn.lock
Fix #171
- Upgrade discord.js dependency
- Upgrade typescript to v5 (required by new discord.js version)
=> chore: update discord.js dependency

src/providers/walletconnectNotify.ts
- [Not using `icon` field anymore ](https://docs.walletconnect.com/web3inbox/sending-notifications#sending-notifications-1)
- Right now we get an error in response, 
```javascript
{
error: 'icon: Validation error: length [{"value": String(""), "min": Number(1), "max": Number(255)}]'
}
```
and it is silent because we are not able to catch these errors
=> [walletConnectNotify] fix: Remove icon field and throw error if there is an error in response

src/providers/discord.ts
Change the colors and statuses of the events we send
Full context here: https://discord.com/channels/955773041898573854/1030772407226601522/1215215100340998254
New events will look something like this:
=> fix: Change status and colours of discord proposal events

src/providers/discord.ts
Fix #103 
Fix an error where the `events` params was being sent as value to the `updated` field
=> fix: fix invalid sql query params on duplicate update

src/providers/index.ts
Disable the xmtp provider because:
- it's the source of the memory leak issue (https://github.com/xmtp/xmtp-js/issues/538)
- the package is using an old api which is sunsetting on june 1st 2025: will require migrating to another package to support their new v3 api
=> fix: disable xmtp provider

README.md, package.json, scripts/setup.ts, src/replay.ts
Fix an error when the `last_mci` is not initialized, like on a brand new database
Added a new `yarn setup` command to prep the database:
- creates the required table if not exist
- populate the table with the initial data (`last_mci`) if not exist
=> fix: fix error when last_mci is not initialized

src/replay.ts
Closes https://github.com/snapshot-labs/workflow/issues/510
<hr/>
For some reason, the `run` fails randomly , but server keeps running, this is causing the server to still run without `run`
In this case all we see is this logs
But can't find any logs from `run`:
```
[replay] Last MCI 91950578
```
<hr/>
I assume it is because of some DB issue from `getLastMci`, i am able to reproduce same logs like above by adding this patch the code
```
diff --git a/src/replay.ts b/src/replay.ts
index 08d9be6..9a68275 100644
--- a/src/replay.ts
+++ b/src/replay.ts
@@ -8,7 +8,12 @@ const hubURL = process.env.HUB_URL || 'https://hub.snapshot.org';
export let last_mci = 0;
+process.on('uncaughtException', () => {});
+
async function getLastMci() {
+  if (Math.random() < 0.5) {
+    throw new Error('Simulated …
```
=> fix: add try catch for entire `run`
